Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Models/leaseItem.cs
namespace ShopLinhKien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("leaseItem")]
    public partial class leaseItem
    {
        [Key]
        public int ID { get; set; }

        public string Name { get; set; }
        public double Price { get; set; }

        public int CateId { get; set; }

        public int Deposits { get; set; }

        public string Description { get; set; }

        public string Content { get; set; }

        public int Status { get; set; }

        public int Order { get; set; }
    }
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Areas/Admin/Controllers/LeaseItemController.cs
using ShopLinhKien.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShopLinhKien.Areas.Admin.Controllers
{
    public class LeaseItemController : BaseController
    {
        private ShopLinhKienDbContext db = new ShopLinhKienDbContext();
        // GET: Admin/LeaseCategory
        public ActionResult Index()
        {
            var list = db.leaseItems.Where(m => m.Status > 0).ToList();
            return View(list);
        }
        public ActionResult Create()
        {
            ViewBag.listCate = db.leaseCategories.Where(m => m.Status != 0).ToList();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(leaseItem leaseItem)
        {

            if (ModelState.IsValid)
            {
                leaseItem.Order = 1;
                //category
                db.leaseItems.Add(leaseItem);
                db.SaveChanges();
                Message.set_flash("Thêm  thành công", "success");
                return RedirectToAction("index");
            }
            ViewBag.listCate = db.leaseCategories.Where(m => m.Status != 0).ToList();
            return View(leaseItem);
        }
        public ActionResult Edit(int? id)
        {
            ViewBag.listCate = db.leaseCategories.Where(m => m.Status != 0).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            leaseItem leaseItem = db.leaseItems.Find(id);
            if (leaseItem == null)
            {
                return HttpNotFound();
            }
            return View(leaseItem);
        }
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Edit(leaseItem leaseItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leaseItem).State = EntityState.Modified;
                Message.set_flash("Sửa  thành công", "success");
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Message.set_flash("Sửa thất bại", "success");
            return View(leaseItem);
        }
        public ActionResult deleteTrash(int id)
        {
            leaseItem leaseItems = db.leaseItems.Find(id);
            db.leaseItems.Remove(leaseItems);
            db.SaveChanges();
            Message.set_flash("Đã xóa vĩnh viễn 1 cấu hình", "success");
            return RedirectToAction("trash");
        }
    }
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Areas/Admin/Views/LeaseItem/Create.cshtml
@model ShopLinhKien.Models.leaseItem

@{
    ViewBag.Title = "Create category";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

}

@{
    List<SelectListItem> listcat = new List<SelectListItem>();
    List<SelectListItem> status = new List<SelectListItem>();
    SelectListItem statusitem1 = new SelectListItem() { Value = "1", Text = "Xuẩt Bản" };
    SelectListItem statusitem2 = new SelectListItem() { Value = "2", Text = "Chưa Xuất bản" };
    status.Add(statusitem1);
    status.Add(statusitem2);


    SelectListItem listcatitem;

    foreach (var item in ViewBag.listCate)
    {

        listcatitem = new SelectListItem() { Value = item.ID + "", Text = "" + item.Name + "" };
        listcat.Add(listcatitem);
    }

}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0 bg-light">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Thêm Danh mục cho thuê</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Admin">Home</a></li>
                        <li class="breadcrumb-item active">Thêm danh mục cho thuê</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


    <section class="container pt-2 card ">
        @Html.Partial("_MessgeAlert")
        <div class="bg-white p-4 ">


            @using (Html.BeginForm("Create", "LeaseItem"))
            {
                @Html.AntiForgeryToken()
                <div class=" row ">
                    <div class="col-md-4">  </div>
                    <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> THÊM DOANH MỤC CHO THUÊ</h3> </div>
                    <div class="col-md-4 ">
                        <div class="float-right">
                            <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                            <a href="~/admin/LeaseCategory" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Hủy</a>
                        </div>
                    </div>
                </div>
                <div class=" row ">
                    <div class="col-md-8">
                        <div>
                            <label for="psw"><span class="text-secondary ">Tên</span></label>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span class="text-secondary ">Mô tả ngắn</span></label>
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span class="text-secondary ">Nội dung cấu hình</span></label>
                            @Html.TextAreaFor(model => model.Content, new
                            {
                                @class = "form-control textarea",
                           @style = "width: 100%;font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"
                            })
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-4">

                        <div>
                            <label for="psw"><span class="text-secondary ">Giá tiền</span></label>
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span class="text-secondary ">Tiền cọc</span></label>
                            @Html.EditorFor(model => model.Deposits, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Deposits, "", new { @class = "text-danger" })
                        </div>
                        <label for="psw"><span class="text-secondary ">Loại cho thuê</span></label>
                        <div>
                            @Html.DropDownListFor(model => model.CateId, listcat, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CateId, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span class="text-secondary ">Trạng Thái</span></label>
                            @Html.DropDownListFor(model => model.Status, status, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>


                </div>
            }
        </div>
    </section>
    <script>
        $("#LeaseItem").addClass("active");
    </script>

    <script>
        $("#post").addClass("active");
        $(function () {
            // Summernote
            $('.textarea').summernote()
        })
    </script>

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Areas/Admin/Views/LeaseItem/Edit.cshtml
@model ShopLinhKien.Models.leaseItem

@{
    ViewBag.Title = "Create category";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

}

@{
    List<SelectListItem> listcat = new List<SelectListItem>();
    List<SelectListItem> status = new List<SelectListItem>();
    SelectListItem statusitem1 = new SelectListItem() { Value = "1", Text = "Xuẩt Bản" };
    SelectListItem statusitem2 = new SelectListItem() { Value = "2", Text = "Chưa Xuất bản" };
    status.Add(statusitem1);
    status.Add(statusitem2);


    SelectListItem listcatitem;

    foreach (var item in ViewBag.listCate)
    {

        listcatitem = new SelectListItem() { Value = item.ID + "", Text = "" + item.Name + "" };
        listcat.Add(listcatitem);
    }

}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0 bg-light">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Thêm Danh mục cho thuê</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Admin">Home</a></li>
                        <li class="breadcrumb-item active">Thêm danh mục cho thuê</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


    <section class="container pt-2 card ">
        @Html.Partial("_MessgeAlert")
        <div class="bg-white p-4 ">
            @using (Html.BeginForm("Edit", "LeaseItem"))
            {
                @Html.AntiForgeryToken()
                <div class=" row ">
                    <div class="col-md-4">  </div>
                    <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> THÊM DOANH MỤC CHO THUÊ</h3> </div>
                    <div class="col-md-4 ">
                        <div class="float-right">
                            <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                            <a href="~/admin/LeaseCategory" class="btn btn-sm bg-danger text-white"><i class="far fa-window-close"></i> Hủy</a>
                        </div>
                    </div>
                </div>
                <div class=" row ">
                    <div class="col-md-8">
                        <div>
                            <label for="psw"><span class="text-secondary ">Tên</span></label>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span class="text-secondary ">Mô tả ngắn</span></label>
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span class="text-secondary ">Nội dung cấu hình</span></label>
                            @Html.TextAreaFor(model => model.Content, new
                            {
                                @class = "form-control textarea",
                           @style = "width: 100%;font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"
                            })
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-4">

                        <div>
                            <label for="psw"><span class="text-secondary ">Giá tiền</span></label>
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span class="text-secondary ">Tiền cọc</span></label>
                            @Html.EditorFor(model => model.Deposits, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Deposits, "", new { @class = "text-danger" })
                        </div>
                        <label for="psw"><span class="text-secondary ">Loại cho thuê</span></label>
                        <div>
                            @Html.DropDownListFor(model => model.CateId, listcat, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CateId, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span class="text-secondary ">Trạng Thái</span></label>
                            @Html.DropDownListFor(model => model.Status, status, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>


                </div>
            }
        </div>
    </section>
    <script>
        $("#LeaseItem").addClass("active");
    </script>

    <script>
        $("#post").addClass("active");
        $(function () {
            // Summernote
            $('.textarea').summernote()
        })
    </script>

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Areas/Admin/Views/LeaseItem/Index.cshtml
@model IEnumerable<ShopLinhKien.Models.leaseItem>

@{
    /**/

    ViewBag.Title = "Category";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quản Lý Loại Sản Phẩm</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Quản Lý Loại Sản Phẩm (category)</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <section class="container-fluid ">
        <div class=" bg-white card  ">

            <div class="row">
                <div class="col-md-9  w-100 ">
                    @Html.Partial("_MessgeAlert")
                </div>
                <div class="col-md-3 ">
                    <div class=" pt-1 ml-5">
                        <a class="text-white btn-sm btn-success" href="~/admin/leaseItem/Create">Add loại cho thuê <i class="fas fa-plus"></i></a>
                        <a class="text-white btn-sm btn-success " href="~/admin/leaseItem/trash">Thùng rác<i class="fas fa-trash"></i></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 p-3">

                    <table id="myTable1" class="table  table-striped table-bordered dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>Tên loại sản phẩm</th>
                                <th>Mô tả</th>
                                <th>Chức Năng</th>
                                <th>ID</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>

                                <td><a class="text-cam font-weight-bold card-link " href=""> @Html.DisplayFor(modelItem => item.Name)</a></td>
                                <td style="font-size:15px;">@Html.DisplayFor(modelItem => item.Description)</td>
                                <td>
                                    <a class="btn btn-sm btn-light text-warning border" href="@Url.Action("Edit", "leaseItem", new { id = item.ID })">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("deleteTrash", "LeaseItem", new { id = item.ID })"> <i class="fas fa-trash-alt"></i></a>
                                </td>
                                <td class="text-cam pt-4">@Html.DisplayFor(modelItem => item.ID)</td>
                            </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </section>

    <script>
        $("#LeaseItem").addClass("active");
    </script>