Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Models/leaseCategory.cs
namespace ShopLinhKien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("leaseCategory")]
    public partial class leaseCategory
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public DateTime created_at { get; set; }

        public int Status { get; set; }
    }
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Areas/Admin/Controllers/LeaseCategoryController.cs
using ShopLinhKien.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShopLinhKien.Areas.Admin.Controllers
{
    public class LeaseCategoryController : BaseController
    {
        private ShopLinhKienDbContext db = new ShopLinhKienDbContext();
        // GET: Admin/LeaseCategory
        public ActionResult Index()
        {
            var list = db.leaseCategories.Where(m => m.Status > 0).ToList();
            return View(list);
        }
        public ActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(leaseCategory leaseCategory)
        {

            if (ModelState.IsValid)
            {
                //category
                string slug = Mystring.ToSlug(leaseCategory.Name.ToString());
                leaseCategory.created_at = DateTime.Now;
                db.leaseCategories.Add(leaseCategory);
                db.SaveChanges();
                Message.set_flash("Thêm  thành công", "success");
                return RedirectToAction("index");
            }
            return View(leaseCategory);
        }
        public ActionResult Edit(int? id)
        {
            ViewBag.listCate = db.Categorys.Where(m => m.status != 0).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            leaseCategory leaseCategory = db.leaseCategories.Find(id);
            if (leaseCategory == null)
            {
                return HttpNotFound();
            }
            return View(leaseCategory);
        }

        [HttpPost]
        public ActionResult Edit(leaseCategory leaseCategory)
        {
            if (ModelState.IsValid)
            {
                string slug = Mystring.ToSlug(leaseCategory.Name.ToString());
                leaseCategory.created_at = DateTime.Now;
                db.Entry(leaseCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Message.set_flash("Sửa thất bại", "success");
            return View(leaseCategory);
        }
        public ActionResult deleteTrash(int id)
        {
            leaseCategory leaseCategories = db.leaseCategories.Find(id);
            db.leaseCategories.Remove(leaseCategories);
            db.SaveChanges();
            Message.set_flash("Đã xóa vĩnh viễn", "success");
            return RedirectToAction("index");
        }
    }
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopLinhKien.Models;
using PagedList;
namespace ShopLinhKien.Controllers
{
    public class SanphamController : Controller
    {
        // GET: Sanpham
        ShopLinhKienDbContext db = new ShopLinhKienDbContext();
        public ActionResult index(int? page)
        {
            var list = db.Products.Where(m => m.status == 1).OrderBy(m=>m.ID);
            if (page == null) page = 1;
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            ViewBag.page = page;
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult _productHome(int id)
        {
            var list = db.Products.Where(m => m.status == 1).
                Where(m => m.catid == id || m.Submenu == id).OrderBy(m => m.ID).OrderBy(m => m.ID).Take(8);
            return View("_productHome", list);
        }
        public ActionResult _productNew()
        {
            var list = db.Products.Where(m => m.status == 1).OrderByDescending(m => m.ID).Take(8);
            return View("_productHome", list);
        }
        public ActionResult _productBestSeller()
        {
            var list = db.Products.Where(m => m.status == 1).OrderByDescending(m => m.sold).Take(8);
            return View("_productHome", list);
        }
        public ActionResult _productsale(int catId)
        {
            var list = db.leaseItems.Where(m => m.Status == 1 && m.CateId == catId).OrderBy(m => m.ID).OrderBy(m => m.ID).Take(6);
            return View("_ProductSale", list);
        }
        
        public ActionResult _lease_category()
        {
            var list = db.leaseCategories.Where(m => m.Status == 1).ToList();
            return View("_lease_category",list);
        }

        public ActionResult category(String slug)
        {
            var catid = db.Categorys.Where(m =>m.slug == slug).First();
            return View("category", catid);
        }

        public ActionResult detail( String slug)
        {
            var list = db.Products.Where(m => m.status == 1 && m.slug == slug).First();
            return View(list);
        }
        public ActionResult cungloai(int catid)
        {
            var list = db.Products.Where(m => m.catid == catid && m.status == 1);
            return View("_cungloai_detail", list.ToList().Take(6));
        }
        public ActionResult subcategory(int catid,string slug, int? page)
        {
            var list = db.Products.Where(m => m.catid == catid || m.Submenu==catid && m.status == 1).OrderBy(m=>m.ID);
            if (page == null) page = 1;
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            ViewBag.page = page;
            ViewBag.slug = slug;
            return View("~/Views/Sanpham/_Subcategory.cshtml", list.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult SearchProduct(string keyw, int? page) {
            @ViewBag.keyw = keyw;
            if (page == null) page = 1;
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            var list = db.Products.Where(m => m.status == 1 && m.name.Contains(keyw)).OrderBy(m => m.ID);
            return View("~/Views/Sanpham/_SearchProduct.cshtml", list.ToPagedList(pageNumber, pageSize));
        }

    }
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Views/Sanpham/_ProductSale.cshtml
@model IEnumerable<ShopLinhKien.Models.leaseItem>
@foreach (var item in Model)
{
        <div class="col-md-4 py-2 ">
            <div class="card">
                <div class="card-body">
                    <div class="card-title text-dark pt-1"><h5 class="font-weight-bold text-info text-center">@item.Name</h5></div>
                    <div class="card-title text-dark pt-1"><h6 class="font-weight-bold text-info text-center">@item.Description</h6></div>
                    <div style="height:430px;" class="p-3" >
                        @Html.Raw(item.Content)
                    </div>
                    <form action="~/leaseOrders/Comfirmm" method="post">                      
                        <input type="hidden" value="@item.ID" name="Id" />                     
                        <div class="card-title text-dark pt-3">
                            <button type="submit" class="btn btn-sm text-white btn-info w-100">Thuê ngay</button>
                            <input type="hidden" value="1" id="sel1" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Views/Sanpham/_SearchProduct.cshtml
@model PagedList.IPagedList<ShopLinhKien.Models.Mproduct>
@using PagedList.Mvc;
@{
    ViewBag.Title = "San pham";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@Html.Action("Mainmenu", "module")

<section class="container-fluid pt-3">
    <div class="container ">
        <div class="row">
            <div class="col-md-3">
                @Html.Action("ListcategoryAll", "module")
            </div>
            <div class="col-md-9">
                <div class="card ">
                    <h3 class="card-header text-xanhduong bg-white">Tìm Kiếm Sản Phẩm</h3>
                    <p>Các sản phẩm có tên "@ViewBag.keyw"</p>
                    <div class="card-body">
                        <div class="row">
                            @foreach (var item in Model)
                            {
                                int sale = (int)item.pricesale;
                                float price = (int)item.price - (int)item.price / 100 * (int)sale;
                                if (sale > 0)
                                {
                                    <div class="col-md-3 py-2 ">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="position-relative">
                                                    <div class="arrow-up">
                                                        <span class=" text-white pl-3">-@sale%</span>
                                                    </div>
                                                    <a href="/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                                                </div>
                                                <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                                                <div class="card-title text-dark">
                                                    <h6 class="font-weight-bold"><strike> @item.price.ToString("N0") VND </strike></h6>
                                                    <h6 class="font-weight-bold text-danger"> @price.ToString("N0") VND</h6>
                                                    <button id="addcartH" onclick="addcart(@item.ID)" class="btn-button-cart w-100  btn-dodam"><i class="fas fa-cart-plus"></i> Mua Ngay</button>
                                                    <input type="hidden" value="1" id="sel1" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="col-md-3 py-2 ">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="position-relative">
                                                    <a href="~/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                                                </div>
                                                <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                                                <div class="card-title text-dark">
                                                    <h6 class="font-weight-bold text-orange"> @item.price.ToString("N0") VND </h6>
                                                    <button id="addcartH" onclick="addcart(@item.ID)" class="btn-button-cart w-100  btn-dodam"><i class="fas fa-cart-plus"></i> Mua Ngay</button>
                                                    <input type="hidden" value="1" id="sel1" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }

                        </div>

                    </div>
                    <ul class="pagination pagination-sm justify-content-center">
                        @{ int i = 1;}

                        @for (int j = i; j <= Model.PageCount; j++)
                        {
                            <li class="page-item"><a class="page-link text-secondary  active-@j" href="/sanpham/?page=@j">@j</a></li>
                            i = j;
                        }
                    </ul>
                </div>

            </div>
        </div>
    </div>
</section>
<style>
    .active-@ViewBag.page{
    background-color: yellow;
    }
</style>

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Views/Sanpham/_Subcategory.cshtml
@model PagedList.IPagedList<ShopLinhKien.Models.Mproduct>

@foreach (var item in Model)
{
    int sale = (int)item.pricesale;
    float price = (int)item.price - (int)item.price / 100 * (int)sale;
    if (sale > 0)
    {
        <div class="col-md-3 py-2 ">
            <div class="card">
                <div class="card-body">
                    <div class="position-relative">
                        <div class="arrow-up">
                            <span class=" text-white pl-3">-@sale%</span>
                        </div>
                        <a href="~/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                    </div>
                    <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                    <div class="card-title text-dark">
                        <h6 class="font-weight-bold"><strike> @item.price.ToString("N0") VND </strike></h6>
                        <h6 class="font-weight-bold text-danger"> @price.ToString("N0") VND</h6>
                        <button id="addcartH" onclick="addcart(@item.ID)" class="btn-button-cart w-100  btn-dodam"><i class="fas fa-cart-plus"></i> Mua Ngay</button>
                        <input type="hidden" value="1" id="sel1" />
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="col-md-3 py-2 ">
            <div class="card">
                <div class="card-body">
                    <div class="position-relative">
                        <a href="~/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                    </div>
                    <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                    <div class="card-title text-dark">
                        <h6 class="font-weight-bold text-orange"> @item.price.ToString("N0") VND </h6>
                        <button id="addcartH" onclick="addcart(@item.ID)" class="btn-button-cart w-100  btn-dodam"><i class="fas fa-cart-plus"></i> Mua Ngay</button>
                        <input type="hidden" value="1" id="sel1" />
                    </div>
                </div>
            </div>
        </div>
    }
}
<div class="col-md-4"></div>
<div class="col-md-4">
    <div class="pagination-content pagination-sm">
        <ul class="pagination  justify-content-center ">


            <li>
                <a href="~/@ViewBag.slug?page=1" class="page-link text-secondary">
                    <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                </a>
            </li>
            <li>
                @{
                    var firstPage = 1;
                    if ((int)Model.PageNumber > 1)
                    {
                        firstPage = (int)Model.PageNumber - 1;
                    }

                    var lastpage = Model.PageNumber;
                    if (lastpage < Model.PageCount)
                    {
                        lastpage = (int)Model.PageNumber + 1;
                    }

                }
                <a href="~/@ViewBag.slug?page=@firstPage" class="page-link text-secondary ">
                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                </a>
            </li>

            @for (int i = Model.PageNumber; i <= Model.PageCount; i++)
            {

                if (i < Model.PageNumber + 5)
                {
                    <li id="active_@i"><a href="~/@ViewBag.slug?page=@i" class="page-link text-secondary">@i  </a></li>
                }

            }
            <li>
                <a href="~/@ViewBag.slug?page=@lastpage" class="page-link text-secondary">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
            </li>
            <li>
                <a href="~/@ViewBag.slug?page=@Model.PageCount" class="page-link text-secondary">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>
</div>
<div class="col-md-4"></div>

<style>
    .active1 {
        background-color: darkorange;
    }
</style>
<script>
    $("#active_@Model.PageNumber").addClass("active1");
</script>

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Views/Sanpham/_cungloai_detail.cshtml
@model IEnumerable<ShopLinhKien.Models.Mproduct>

@foreach (var item in Model)
{
    int sale = (int)item.pricesale;
    float price = (int)item.price - (int)item.price / 100 * (int)sale;
    if (sale > 0)
    {
        <div class="col-md-2 py-2 ">
            <div class="card">
                <div class="card-body">
                    <div class="position-relative">
                        <div class="arrow-up">
                            <span class=" text-white pl-3">-@sale%</span>
                        </div>
                        <a href="~/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                    </div>
                    <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                    <div class="card-title text-dark">
                        <h6 class="font-weight-bold"><strike> @item.price.ToString("N0") VND </strike></h6>
                        <h6 class="font-weight-bold text-danger"> @price.ToString("N0") VND</h6>
                        <a href="@item.slug" class="btn btn-sm text-white btn-dodam">Xem chi tiết</a>
                     
                        <input type="hidden" value="1" id="sel1" />
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="col-md-2 py-2 ">
            <div class="card">
                <div class="card-body">
                    <div class="position-relative">
                        <a href="~/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                    </div>
                    <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                    <div class="card-title text-dark">
                        <h6 class="font-weight-bold text-orange"> @item.price.ToString("N0") VND </h6>
                        <a href="@item.slug" class="btn btn-sm text-white btn-dodam">Xem chi tiết</a>
                        <input type="hidden" value="1" id="sel1" />
                    </div>
                </div>
            </div>
        </div>
    }
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Views/Sanpham/_lease_category.cshtml
@model IEnumerable<ShopLinhKien.Models.leaseCategory>

@foreach (var item in Model)
{
    <section class="container-fluid pt-3">
        <div class="container ">
            <div class="card bg-light">
                <h3 class="card-header text-xanhduong bg-white text-center font-weight-bold">@item.Name</h3>
                <div class="card-body">
                    <div class="row">
                        @Html.Action("_productsale", "Sanpham", new {catId = item.ID})
                    </div>
                </div>
    </section>
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Views/Sanpham/_productHome.cshtml
@model IEnumerable<ShopLinhKien.Models.Mproduct>
@foreach (var item in Model)
{
    int sale = (int)item.pricesale;
    float price = (int)item.price - (int)item.price/100*(int)sale;
    if (sale > 0)
    {
        <div class="col-md-3 py-2 ">
            <div class="card">
                <div class="card-body">
                    <div class="position-relative">
                        <div class="arrow-up">
                            <span class=" text-white pl-3">-@sale%</span>
                        </div>
                        <a href="~/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                    </div>
                    <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                    <div class="card-title text-dark">
                        <h6 class="font-weight-bold"><strike> @item.price.ToString("N0") VND </strike></h6>
                        <h6 class="font-weight-bold text-danger"> @price.ToString("N0") VND</h6>
                        <a href="@item.slug" class="btn btn-sm text-white btn-warning"><i class="fas fa-eye"></i>Chi tiết</a>
                        <button id="addcartH" onclick="addcart(@item.ID)" class="btn btn-sm text-white   btn-dodam"><i class="fas fa-cart-plus"></i> Thêm GH</button>
                        <input type="hidden" value="1" id="sel1" />
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="col-md-3 py-2 ">
            <div class="card">
                <div class="card-body">
                    <div class="position-relative">                    
                        <a href="~/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                    </div>
                    <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                    <div class="card-title text-dark">
                        <h6 class="font-weight-bold text-orange"> @item.price.ToString("N0") VND </h6>
                        <a href="@item.slug" class="btn btn-sm text-white btn-warning"><i class="fas fa-eye"></i>Chi tiết</a>
                        <button id="addcartH" onclick="addcart(@item.ID)" class="btn btn-sm text-white   btn-dodam"><i class="fas fa-cart-plus"></i> Thêm GH</button>
                        <input type="hidden" value="1" id="sel1" />
                    </div>
                </div>
            </div>
        </div>
    }
}

Project4-Nhom VIP/ShopLinhKien/ShopLinhKien/Views/Sanpham/index.cshtml
@model PagedList.IPagedList<ShopLinhKien.Models.Mproduct>
@using PagedList.Mvc;
@{
    ViewBag.Title = "San pham";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@Html.Action("Mainmenu", "module")

<section class="container-fluid pt-3">
    <div class="container ">
        <div class="row">
            <div class="col-md-3">
                @Html.Action("ListcategoryAll", "module")
            </div>
            <div class="col-md-9">
                <div class="card ">
                    <h3 class="card-header text-xanhduong bg-white">Tất Cả Sản Phẩm</h3>
                    <div class="card-body">
                        <div class="row">
                            @foreach (var item in Model)
                            {
                                int sale = (int)item.pricesale;
                                float price = (int)item.price - (int)item.price / 100 * (int)sale;
                                if (sale > 0)
                                {
                                    <div class="col-md-3 py-2 ">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="position-relative">
                                                    <div class="arrow-up">
                                                        <span class=" text-white pl-3">-@sale%</span>
                                                    </div>
                                                    <a href="~/item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                                                </div>
                                                <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                                                <div class="card-title text-dark">
                                                    <h6 class="font-weight-bold"><strike> @item.price.ToString("N0") VND </strike></h6>
                                                    <h6 class="font-weight-bold text-danger"> @price.ToString("N0") VND</h6>
                                                    <button id="addcartH" onclick="addcart(@item.ID)" class="btn-button-cart w-100  btn-dodam"><i class="fas fa-cart-plus"></i> Mua Ngay</button>
                                                    <input type="hidden" value="1" id="sel1" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="col-md-3 py-2 ">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="position-relative">
                                                    <a href="~/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                                                </div>
                                                <div class="card-title text-dark pt-1"><h6><a href="~/@item.slug" class="text-danger">@item.name</a></h6></div>
                                                <div class="card-title text-dark">
                                                    <h6 class="font-weight-bold text-orange"> @item.price.ToString("N0") VND </h6>
                                                    <button id="addcartH" onclick="addcart(@item.ID)" class="btn-button-cart w-100  btn-dodam"><i class="fas fa-cart-plus"></i> Mua Ngay</button>
                                                    <input type="hidden" value="1" id="sel1" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }

                        </div>

                    </div>
                    <div class="pagination-content pagination-sm">
                        <ul class="pagination  justify-content-center">


                            <li>
                                <a href="~/sanpham?page=1" class="page-link text-secondary">
                                    <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                                </a>
                            </li>
                            <li>
                                @{
                                    var firstPage = 1;
                                    if ((int)Model.PageNumber > 1)
                                    {
                                        firstPage = (int)Model.PageNumber - 1;
                                    }

                                    var lastpage = Model.PageNumber;
                                    if (lastpage < Model.PageCount)
                                    {
                                        lastpage = (int)Model.PageNumber + 1;
                                    }

                                }
                                <a href="~/sanpham?page=@firstPage" class="page-link text-secondary ">
                                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                                </a>
                            </li>

                            @for (int i = Model.PageNumber; i <= Model.PageCount; i++)
                            {

                                if (i < Model.PageNumber + 5)
                                {
                                    <li id="active_@i"><a href="~/sanpham?page=@i" class="page-link text-secondary">@i  </a></li>
                                }

                            }
                            <li>
                                <a href="~/sanpham?page=@lastpage" class="page-link text-secondary">
                                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                                </a>
                            </li>
                            <li>
                                <a href="~/sanpham?page=@Model.PageCount" class="page-link text-secondary">
                                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                </a>
                            </li>
                        </ul>
                    </div>




                </div>

            </div>
        </div>
    </div>
</section>
<style>
    .active1 {
        background-color: darkorange;
    }
</style>
<script>
    $("#active_@Model.PageNumber").addClass("active1");
</script>